# Generated by Django 5.2.18 on 2026-10-06 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Currency Config',
                'verbose_name_plural': 'Currency Configs',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='KES', max_length=3)),
                ('target_currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fallback', models.BooleanField(default=False, help_text='True if the API was unavailable and this is a cached fallback')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'indexes': [models.Index(fields=['target_currency', 'fetched_at'], name='currency_ex_target__562018_idx')],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
