# Generated by Django 5.2.18 on 2026-10-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('vehicle_page_views', models.PositiveIntegerField(default=0)),
                ('mobile_views', models.PositiveIntegerField(default=0)),
                ('desktop_views', models.PositiveIntegerField(default=0)),
                ('tablet_views', models.PositiveIntegerField(default=0)),
                ('top_paths', models.JSONField(blank=True, default=list)),
                ('top_referers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_p_path_53ae0e_idx'), models.Index(fields=['created_at', 'is_bot'], name='analytics_p_created_6edeae_idx'), models.Index(fields=['session_key'], name='analytics_p_session_1f2553_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopVehicleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Top Vehicle Stat',
                'verbose_name_plural': 'Top Vehicle Stats',
                'ordering': ['date', 'rank'],
                'unique_together': {('date', 'vehicle')},
            },
        ),
        migrations.CreateModel(
            name='VehicleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle View',
                'verbose_name_plural': 'Vehicle Views',
                'indexes': [models.Index(fields=['vehicle', 'created_at'], name='analytics_v_vehicle_392cb6_idx'), models.Index(fields=['created_at'], name='analytics_v_created_5140c3_idx')],
            },
        ),
    ]
