# Generated by Django 5.2.18 on 2026-10-06 20:13

import core.utils
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, help_text='Group label e.g. Safety, Comfort, Technology', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='vehicles_ca_slug_5f25ab_idx'), models.Index(fields=['is_popular', 'sort_order'], name='vehicles_ca_is_popu_4ea6f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='makes/logos/')),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Make',
                'verbose_name_plural': 'Makes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='vehicles_ma_slug_7a2e77_idx'), models.Index(fields=['is_popular', 'sort_order'], name='vehicles_ma_is_popu_598a4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('stock_number', models.CharField(blank=True, help_text='Auto-generated if left blank e.g. VEH-1024', max_length=50, unique=True)),
                ('variant', models.CharField(blank=True, help_text='Trim/grade e.g. TX-L, Sport', max_length=100)),
                ('year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('FOREIGN_USED', 'Foreign Used'), ('LOCALLY_USED', 'Locally Used'), ('RECONDITIONED', 'Reconditioned')], db_index=True, max_length=20)),
                ('body_type', models.CharField(blank=True, choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup / Truck'), ('VAN', 'Van / Minivan'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('WAGON', 'Station Wagon'), ('BUS', 'Bus / Matatu'), ('TRUCK', 'Truck / Lorry'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Price in KES. Leave blank for Price on Request.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, help_text="Previous price — shown as 'Was KSh X' if set", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pricing_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('NEGOTIABLE', 'Negotiable'), ('PRICE_ON_REQUEST', 'Price on Request')], db_index=True, default='NEGOTIABLE', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('mileage', models.PositiveIntegerField(blank=True, db_index=True, help_text='Mileage in km', null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('PLUGIN', 'Plug-in Hybrid'), ('LPG', 'LPG'), ('CNG', 'CNG')], db_index=True, max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT'), ('DCT', 'Dual-Clutch (DCT)'), ('SEMI_AUTO', 'Semi-Automatic')], db_index=True, max_length=20)),
                ('drivetrain', models.CharField(blank=True, choices=[('FWD', 'Front-Wheel Drive (FWD)'), ('RWD', 'Rear-Wheel Drive (RWD)'), ('AWD', 'All-Wheel Drive (AWD)'), ('4WD', 'Four-Wheel Drive (4WD)')], db_index=True, max_length=10)),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, help_text='Engine displacement in litres e.g. 2.8', max_digits=5, null=True)),
                ('engine_power', models.PositiveSmallIntegerField(blank=True, help_text='Power in horsepower (hp)', null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=80)),
                ('interior_color', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=150)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], db_index=True, default='AVAILABLE', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('new_arrival', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('inquiry_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.category')),
                ('features', models.ManyToManyField(blank=True, related_name='vehicles', to='vehicles.feature')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.make')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logbook_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PROCESSING', 'Processing'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20)),
                ('import_docs', models.CharField(choices=[('AVAILABLE', 'Available'), ('PROCESSING', 'Processing'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20, verbose_name='Import Documents')),
                ('duty_status', models.CharField(choices=[('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('NOT_PAID', 'Not Paid'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('transfer_status', models.CharField(choices=[('READY', 'Ready'), ('PROCESSING', 'Processing'), ('NOT_READY', 'Not Ready')], default='NOT_READY', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes only')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Documentation',
                'verbose_name_plural': 'Vehicle Documentation',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.make')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['make__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='VehicleVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('NOT_INSPECTED', 'Not Inspected')], default='NOT_INSPECTED', max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, help_text='Internal only')),
                ('mileage_verified', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=20)),
                ('document_verified', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending'), ('NOT_VERIFIED', 'Not Verified')], default='NOT_VERIFIED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Verification',
                'verbose_name_plural': 'Vehicle Verifications',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['vehicle', 'changed_at'], name='vehicles_pr_vehicle_51e17f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Vehicle Created'), ('UPDATED', 'Vehicle Updated'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('PRICE_CHANGED', 'Price Changed'), ('FEATURED', 'Marked as Featured'), ('UNFEATURED', 'Removed from Featured'), ('RESERVED', 'Marked as Reserved'), ('SOLD', 'Marked as Sold'), ('ARCHIVED', 'Archived'), ('IMAGE_ADDED', 'Image Added'), ('IMAGE_REMOVED', 'Image Removed')], db_index=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'created_at'], name='vehicles_au_vehicle_003e63_idx'), models.Index(fields=['action', 'created_at'], name='vehicles_au_action_493f83_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.generate_vehicle_image_path, validators=[core.utils.validate_image_upload])),
                ('thumbnail', models.ImageField(blank=True, upload_to='vehicles/thumbs/')),
                ('webp_image', models.ImageField(blank=True, upload_to='vehicles/webp/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive alt text for accessibility and SEO', max_length=200)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['vehicle', 'is_primary'], name='vehicles_ve_vehicle_059fc5_idx'), models.Index(fields=['vehicle', 'sort_order'], name='vehicles_ve_vehicle_2cd859_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['make', 'slug'], name='vehicles_ve_make_id_115292_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['slug'], name='vehicles_ve_slug_99a063_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('make', 'name')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_published', 'status'], name='idx_pub_status'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_published', 'featured'], name='idx_pub_featured'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_published', 'new_arrival'], name='idx_pub_arrival'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_published', 'status', 'price'], name='idx_pub_status_price'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_published', 'status', 'year'], name='idx_pub_status_year'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_published', 'status', 'mileage'], name='idx_pub_status_mile'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model', 'year'], name='idx_make_model_year'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['published_at'], name='idx_published_at'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('previous_price__gte', 0), ('previous_price__isnull', True), _connector='OR'), name='previous_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900), ('year__lte', 2100)), name='year_valid_range'),
        ),
    ]
